name: Growfinitys Scheduler

on:
  schedule:
    # Hourly signals (UTC)
    - cron: "0 * * * *"
    # Daily recap (21:00 Amman)
    - cron: "0 18 * * *"
    # Daily cleanup (03:00 Amman)
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  run-scheduled-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Determine which schedule fired
        id: when
        run: |
          now_min=$(date -u +%M)
          now_hour=$(date -u +%H)
          if [ "$now_min" = "00" ]; then
            if [ "$now_hour" = "18" ]; then echo "task=daily_recap" >> $GITHUB_OUTPUT; exit 0; fi
            if [ "$now_hour" = "00" ]; then echo "task=daily_cleanup" >> $GITHUB_OUTPUT; exit 0; fi
            echo "task=hourly" >> $GITHUB_OUTPUT; exit 0
          fi
          echo "task=unknown" >> $GITHUB_OUTPUT

      - name: Hourly — generate signals for all tiers
        if: steps.when.outputs.task == 'hourly'
        run: |
          set -e
          curl -sS -X POST "$SITE_URL/api/zapier/ai-signal?auth=$ZAPIER_SECRET" \
            -H "Content-Type: application/json" \
            -d '{"audience":"basic","count":3}'
          curl -sS -X POST "$SITE_URL/api/zapier/ai-signal?auth=$ZAPIER_SECRET" \
            -H "Content-Type: application/json" \
            -d '{"audience":"pro","count":5}'
          curl -sS -X POST "$SITE_URL/api/zapier/ai-signal?auth=$ZAPIER_SECRET" \
            -H "Content-Type: application/json" \
            -d '{"audience":"vip","count":6}'

      - name: Daily Recap — 21:00 Amman
        if: steps.when.outputs.task == 'daily_recap'
        run: |
          set -e
          curl -sS -X POST "$SITE_URL/api/zapier/daily-summary?auth=$ZAPIER_SECRET" \
            -H "Content-Type: application/json" \
            -d '{"mode":"per-tier"}'

      - name: Daily Cleanup — 03:00 Amman
        if: steps.when.outputs.task == 'daily_cleanup'
        run: |
          set -e
          curl -sS "$SITE_URL/api/cron/daily?auth=$ZAPIER_SECRET"

    env:
      SITE_URL: ${{ secrets.SITE_URL }}
      ZAPIER_SECRET: ${{ secrets.ZAPIER_SECRET }}
